### ISSUE TITLE
ข้อสงสัยเกี่ยวกับสิ่งที่ต้องอยู่ในไฟล์ XML

### ISSUE THREAD

**Issue by wirunpong-j** [it-kmitl-2018/group3-backend#11]
จากตัวอย่าง xml ที่ให้มามีข้อมูลบางส่วนที่ไม่ปรากฏในตารางใดๆ เลย เช่น 
```xml
<rsm:TaxInvoice_CrossIndustryInvoice
xmlns:ram="urn:etda:uncefact:data:standard:TaxInvoice_ReusableAggregateBusinessInformationEntity:2"
xmlns:rsm="urn:etda:uncefact:data:standard:TaxInvoice_CrossIndustryInvoice:2"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="urn:etda:uncefact:data:standard:TaxInvoice_CrossIndustryInvoice:2 file:../data
/standard/TaxInvoice_CrossIndustryInvoice_2p0.xsd">
```

และข้อมูลในส่วน Signature อยากทราบว่า จะเอามาจากไหน 
@champillon

**Comment by champillon** [comment]
@wirunpong-j ช่วยบอกหน้าของเอกสารหน่อยครับ พี่จะได้ตามไปดู หรือช่วย capture มาให้ก็ได้ จะได้ตรงกัน

**Comment by wirunpong-j** [comment]
จากเอกสาร Requirement ตัวล่าสุดที่พี่ลงอะครับ
พวก Tag = xmlns:ram, xmlns:xsi, xsi:schemaLocation อะครับ
![](https://lh4.googleusercontent.com/TmFY2FSIAtt71XBMV0OTylh4_LpMcd2P9X8tYI-gCrvB0zPQRLsWTGiF2YkmPaW9ns_m36Hi_ACKdIapt-_Y=w3175-h1700-rw)

**Comment by champillon** [comment]
@wirunpong-j รูปไม่ขึ้นจร้าาาาาาาาา

**Comment by wirunpong-j** [comment]
![2404b43b5803c238189ca125404f6eb0.png](https://www.img.in.th/images/2404b43b5803c238189ca125404f6eb0.png)

**Comment by champillon** [comment]
พวกนี้เป็น namespace ของ XML ครับ จริงๆ สร้างจาก XSD
เดี๋ยวพี่ส่งไฟล์ XSD ให้นะครับ ใน Facebook Group

**Comment by champillon** [comment]
อันนี้ครับ -> https://etax.rd.go.th/etax_staticpage/app/download/XMLSchemaV2.zip
