### ISSUE TITLE
Please update team convention

### ISSUE THREAD

**Issue by chin8628** [it-kmitl-2018/group3-backend#2]
For god sake, The old one is sucks. I think it should be fixed. ~

**Comment by XIIKJIIX** [comment]
Ok, got it.

**Comment by XIIKJIIX** [comment]
I already got a pull request. Ready to merge. #1 @chin8628

**Comment by chin8628** [comment]
Thanks. Just wait the leader approves it! @champillon

**Comment by Chiibi** [comment]
Roger ! supreme leader.
