### ISSUE TITLE
Need to initialise project, what tech stack we should use?

### ISSUE THREAD

**Issue by XIIKJIIX** [it-kmitl-2018/group3-backend#3]
Spring Boot + React? any suggestion?

**Comment by chin8628** [comment]
We're discussing, just wait a moment. 
How about you guys? @wirunpong-j @patcharapon-j

**Comment by champillon** [comment]
If you need another repo to separate front-end and back-end kindly tell me.

**Comment by chin8628** [comment]
OK, Let's go! @XIIKJIIX

**Comment by XIIKJIIX** [comment]
@champillon Yes! I would like to separate it. Thanks for your help.

**Comment by Chiibi** [comment]
Sound good!!.

**Comment by champillon** [comment]
doing it this late night and may rename this repo to group3-backend.

**Comment by champillon** [comment]
repo front-end krub => https://github.com/it-kmitl-2018/group3-frontend

Kindly make the CONVENTION.md for that repo also krub

**Comment by champillon** [comment]
renamed group3 => group3-backend (may need to reclone the git na krub because the URL have changed)

**Comment by XIIKJIIX** [comment]
@champillon Thank you!
