### ISSUE TITLE
Just a suggestion to Bind the Model with the View first for avoiding Over-engineering

### ISSUE THREAD

**Issue by champillon** [it-kmitl-2018/group3-backend#39]
Just a suggestion to Bind the Model with the View first for avoiding Over-engineering

See this pic, the guideline to Agile way
![1 qinsg4wh_bdn-vimjuh6ng](https://user-images.githubusercontent.com/1620789/36942243-37909742-1fa0-11e8-9d1a-c6d86e05bb8c.png)

**Comment by chin8628** [comment]
ถ้าอย่างนี้ก็แปลว่า ควรทำ view ที่เป็น post-api สำหรับยิงข้อมูลจากหน้า Ui ใส่ฟอร์มไปทีละ Model ก่อนหรอครับ

**Comment by champillon** [comment]
ใช่ ใช่ ใช่
